# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [ ]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [ ]:
# Create a 1-dimensional NumPy array using np.array()
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)

# Create a 2-dimensional NumPy array using np.array()
my_array_2d = np.array([[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]])
print(my_array_2d)

# Create a 3-dimensional Numpy array using np.array()
import numpy as np

# Creating a 3-dimensional NumPy array
my_array_3d = np.array([[[1, 2, 3],
                         [4, 5, 6],
                         [7, 8, 9]],

                        [[10, 11, 12],
                         [13, 14, 15],
                         [16, 17, 18]],

                        [[19, 20, 21],
                         [22, 23, 24],
                         [25, 26, 27]]])
print(my_array_3d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [ ]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
shape = my_array.shape  # Shape of the array
dimensions = my_array.ndim  # Number of dimensions
data_type = my_array.dtype  # Data type of the elements
size = my_array.size  # Number of elements in the array
array_type = type(my_array)  # Type of the array

# Print the attributes
print("Shape:", shape)
print("Number of dimensions:", dimensions)
print("Data type:", data_type)
print("Size:", size)
print("Type:", array_type)

Shape: (5,)
Number of dimensions: 1
Data type: int64
Size: 5
Type: <class 'numpy.ndarray'>


In [ ]:
# Attributes of 2-dimensional array
shape = my_array_2d.shape  # Shape of the array
dimensions = my_array_2d.ndim  # Number of dimensions
data_type = my_array_2d.dtype  # Data type of the elements
size = my_array_2d.size  # Number of elements in the array
array_type = type(my_array_2d)  # Type of the array

# Print the attributes
print("Shape:", shape)
print("Number of dimensions:", dimensions)
print("Data type:", data_type)
print("Size:", size)
print("Type:", array_type)

Shape: (3, 3)
Number of dimensions: 2
Data type: int64
Size: 9
Type: <class 'numpy.ndarray'>


In [ ]:
# Attributes of 3-dimensional array
shape = my_array_3d.shape  # Shape of the array
dimensions = my_array_3d.ndim  # Number of dimensions
data_type = my_array_3d.dtype  # Data type of the elements
size = my_array_3d.size  # Number of elements in the array
array_type = type(my_array_3d)  # Type of the array

# Print the attributes
print("Shape:", shape)
print("Number of dimensions:", dimensions)
print("Data type:", data_type)
print("Size:", size)
print("Type:", array_type)

Shape: (3, 3, 3)
Number of dimensions: 3
Data type: int64
Size: 27
Type: <class 'numpy.ndarray'>


In [ ]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
my_array_2d = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])
df = pd.DataFrame(my_array_2d)
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


In [ ]:
# Create an array of shape (10, 2) with only ones
ones_array = np.ones((10, 2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_array = np.zeros((7, 2, 3))
print(zeros_array)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
# Create an array within a range of 0 and 100 with step 3
my_array = np.arange(0, 100, 3)
print(my_array)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [ ]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 11, size=(7, 2))
print(random_array)

[[ 7  7]
 [ 4  1]
 [ 1  9]
 [ 1  1]
 [10  8]
 [ 2  3]
 [ 0  2]]


In [ ]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_float_array = np.random.rand(3, 5)
print(random_float_array)

[[0.81188938 0.15958723 0.07605891 0.93344339 0.56490228]
 [0.3912913  0.98528906 0.02464361 0.17096416 0.95827307]
 [0.44107623 0.40343326 0.70410181 0.21457194 0.18358812]]


In [ ]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(0, 11, size=(4, 6))
print(random_array)

[[ 6  3 10  7  4  6]
 [ 9  2  6 10 10  7]
 [ 4  3  7  7  2  5]
 [ 4  1  7  5  1  4]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [ ]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
random_array = np.random.randint(1, 11, size=(3, 7))

# and save it to a variable
print(random_array)

# Find the unique numbers in the array you just created
unique_numbers = np.unique(random_array)
print("Unique numbers are:", unique_numbers)

[[10  9 10  5  2  4  7]
 [ 8  3  1  4  2  8  4]
 [ 2  6  6 10  4  6  2]]
Unique numbers are: [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Find the 0'th index of the latest array you created
first_row = random_array[0]
print(first_row)

[10  9 10  5  2  4  7]


In [ ]:
# Get the first 2 rows of latest array you created
first_two_rows = random_array[:2, :]
print(first_two_rows)

[[10  9 10  5  2  4  7]
 [ 8  3  1  4  2  8  4]]


In [ ]:
# Get the first 2 values of the first 2 rows of the latest array
first_two_values = random_array[:2, :2]
print(first_two_values)

[[10  9]
 [ 8  3]]


In [ ]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array = np.random.randint(0, 11, size=(3, 5))
ones_array = np.ones((3, 5))
print("Random Array:")
print(random_array)
print("\nArray of Ones:")
print(ones_array)


Random Array:
[[9 1 9 3 7]
 [6 8 7 4 1]
 [4 7 9 8 8]]

Array of Ones:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Add the two arrays together
sum_array = random_array + ones_array
print("Sum of the arrays:")
print(sum_array)

Sum of the arrays:
[[10.  2. 10.  4.  8.]
 [ 7.  9.  8.  5.  2.]
 [ 5.  8. 10.  9.  9.]]


In [ ]:
# Create another array of ones of shape (5, 3)
ones_array_5x3 = np.ones((5, 3))
print(ones_array_5x3)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Try add the array of ones and the other most recent array together
random_array = np.random.randint(0, 11, size=(3, 5))
ones_array = np.ones((3, 5))
sum_array = random_array + ones_array
ones_array_5x3 = np.ones((5, 3))
ones_array_transposed = ones_array_5x3.T
final_sum_array = sum_array + ones_array_transposed
print("Sum of the arrays:")
print(final_sum_array)

Sum of the arrays:
[[ 2. 10.  8. 10.  9.]
 [ 2.  9.  9. 12.  4.]
 [ 2.  9.  4.  4.  2.]]


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [ ]:
# Create another array of ones of shape (3, 5)
import numpy as np
ones_array_another = np.ones((3, 5))
print(ones_array_another)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# Subtract the new array of ones from the other most recent array
random_array = np.random.randint(0, 11, size=(3, 5))
ones_array = np.ones((3, 5))
subtracted_array = random_array - ones_array
print("Result of subtraction:")
print(subtracted_array)

Result of subtraction:
[[ 7.  9. -1.  4.  7.]
 [ 5.  1.  5.  7. -1.]
 [ 3.  8.  7. -1.  1.]]


In [ ]:
# Multiply the ones array with the latest array
ones_array = np.ones_like(random_array)
multiplied_array = random_array * ones_array
print("Result of multiplication:")
print(multiplied_array)

Result of multiplication:
[[ 8 10  0  5  8]
 [ 6  2  6  8  0]
 [ 4  9  8  0  2]]


In [ ]:
# Take the latest array to the power of 2 using '**'
power_of_2_array = random_array ** 2
print("Result of raising the array to the power of 2:")
print(power_of_2_array)

Result of raising the array to the power of 2:
[[ 64 100   0  25  64]
 [ 36   4  36  64   0]
 [ 16  81  64   0   4]]


In [ ]:
# Do the same thing with np.square()
power_of_2_array = np.square(random_array)
print("Result of computing the square of the array:")
print(power_of_2_array)

Result of computing the square of the array:
[[ 64 100   0  25  64]
 [ 36   4  36  64   0]
 [ 16  81  64   0   4]]


In [ ]:
# Find the mean of the latest array using np.mean()
mean_of_array = np.mean(random_array)
print("Mean of the array:", mean_of_array)

Mean of the array: 5.066666666666666


In [ ]:
# Find the maximum of the latest array using np.max()
max_of_array = np.max(random_array)
print("Maximum value of the array:", max_of_array)

Maximum value of the array: 10


In [ ]:
# Find the minimum of the latest array using np.min()
min_of_array = np.min(random_array)
print("Minimum value of the array:", min_of_array)

Minimum value of the array: 0


In [ ]:
# Find the standard deviation of the latest array
std_deviation_of_array = np.std(random_array)
print("Standard deviation of the array:", std_deviation_of_array)

Standard deviation of the array: 3.3954217541991585


In [ ]:
# Find the variance of the latest array
variance_of_array = np.var(random_array)
print("Variance of the array:", variance_of_array)

Variance of the array: 11.528888888888892


In [ ]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = random_array.reshape(3, 5, 1)
print("Reshaped array:")
print(reshaped_array)

Reshaped array:
[[[ 8]
  [10]
  [ 0]
  [ 5]
  [ 8]]

 [[ 6]
  [ 2]
  [ 6]
  [ 8]
  [ 0]]

 [[ 4]
  [ 9]
  [ 8]
  [ 0]
  [ 2]]]


In [ ]:
# Transpose the latest array
transposed_array = np.transpose(random_array)
print("Transposed array:")
print(transposed_array)

Transposed array:
[[ 8  6  4]
 [10  2  9]
 [ 0  6  8]
 [ 5  8  0]
 [ 8  0  2]]


What does the transpose do?

In [ ]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_3x3 = np.random.randint(0, 11, size=(3, 3))
array_3x2 = np.random.randint(0, 11, size=(3, 2))
print("Array of size (3, 3):")
print(array_3x3)
print("\nArray of size (3, 2):")
print(array_3x2)

Array of size (3, 3):
[[ 1 10  5]
 [10  3  7]
 [ 0  0  7]]

Array of size (3, 2):
[[ 2  6]
 [ 5 10]
 [ 3  8]]


In [ ]:
# Perform a dot product on the two newest arrays you created
dot_product_result = np.dot(array_3x3, array_3x2)
print("Dot product result:")
print(dot_product_result)

Dot product result:
[[ 67 146]
 [ 56 146]
 [ 21  56]]


In [ ]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
import numpy as np
array1_4x3 = np.random.randint(0, 11, size=(4, 3))
array2_4x3 = np.random.randint(0, 11, size=(4, 3))
print("Array 1 of size (4, 3):")
print(array1_4x3)
print("\nArray 2 of size (4, 3):")
print(array2_4x3)

Array 1 of size (4, 3):
[[ 0  8 10]
 [ 6  5  7]
 [ 4  5 10]
 [ 2  2  2]]

Array 2 of size (4, 3):
[[6 4 0]
 [1 1 1]
 [2 9 9]
 [4 1 2]]


In [ ]:
# Perform a dot product on the two newest arrays you created
dot_product_result = np.dot(array1_4x3, array2_4x3.T)
print("Dot product result:")
print(dot_product_result)

Dot product result:
[[ 32  18 162  28]
 [ 56  18 120  43]
 [ 44  19 143  41]
 [ 20   6  40  14]]


It doesn't work. How would you fix it?

In [ ]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
array1_transposed = array1_4x3.T
dot_product_result = np.dot(array1_transposed, array2_4x3)
print("Dot product result:")
print(dot_product_result)

Dot product result:
[[ 22  44  46]
 [ 71  84  54]
 [ 95 139 101]]


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
shape = (4, 3)
array1 = np.random.randint(0, 11, size=shape)
array2 = np.random.randint(0, 11, size=shape)
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

Array 1:
[[9 0 3]
 [7 5 1]
 [6 1 2]
 [4 8 5]]

Array 2:
[[3 4 0]
 [2 9 0]
 [3 3 7]
 [3 0 4]]


In [ ]:
# Compare the two arrays with '>'
comparison_result = array1 > array2
print("Comparison result (array1 > array2):")
print(comparison_result)

Comparison result (array1 > array2):
[[ True False  True]
 [ True False  True]
 [ True False False]
 [ True  True  True]]


What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='
comparison_result = array1 >= array2
print("Comparison result (array1 > array2):")
print(comparison_result)

Comparison result (array1 > array2):
[[ True False  True]
 [ True False  True]
 [ True False False]
 [ True  True  True]]


In [ ]:
# Find which elements of the first array are greater than 7
elements_greater_than_7 = array1[array1 > 7]
print("Elements of the first array greater than 7:")
print(elements_greater_than_7)

Elements of the first array greater than 7:
[9 8]


In [ ]:
# Which parts of each array are equal? (try using '==')
array2=array1
equality_result = array1 == array2
print("Equality result (array1 == array2):")
print(equality_result)

Equality result (array1 == array2):
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# Sort one of the arrays you just created in ascending order
sorted_array1 = np.sort(array1)
print("Original array:")
print(array1)
print("\nSorted array in ascending order:")
print(sorted_array1)

Original array:
[[9 0 3]
 [7 5 1]
 [6 1 2]
 [4 8 5]]

Sorted array in ascending order:
[[0 3 9]
 [1 5 7]
 [1 2 6]
 [4 5 8]]


In [ ]:
# Sort the indexes of one of the arrays you just created
sorted_indexes = np.argsort(array1)
print("Original array:")
print(array1)
print("\nSorted indexes:")
print(sorted_indexes)

Original array:
[[9 0 3]
 [7 5 1]
 [6 1 2]
 [4 8 5]]

Sorted indexes:
[[1 2 0]
 [2 1 0]
 [1 2 0]
 [0 2 1]]


In [ ]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(array1)
row_index, col_index = np.unravel_index(max_index, shape)
print("Original array:")
print(array1)
print("\nIndex with the maximum value:", (row_index, col_index))
print("Maximum value in the array:", array1[row_index, col_index])

Original array:
[[9 0 3]
 [7 5 1]
 [6 1 2]
 [4 8 5]]

Index with the maximum value: (0, 0)
Maximum value in the array: 9


In [ ]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(array1)
row_index, col_index = np.unravel_index(min_index, shape)
print("Original array:")
print(array1)
print("\nIndex with the minimum value:", (row_index, col_index))
print("Minimum value in the array:", array1[row_index, col_index])

Original array:
[[9 0 3]
 [7 5 1]
 [6 1 2]
 [4 8 5]]

Index with the minimum value: (0, 1)
Minimum value in the array: 0


In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
max_indexes_axis1 = np.argmax(array1, axis=1)
print("Original array:")
print(array1)
print("\nIndexes with maximum values along axis=1:")
print(max_indexes_axis1)

Original array:
[[9 0 3]
 [7 5 1]
 [6 1 2]
 [4 8 5]]

Indexes with maximum values along axis=1:
[0 0 0 1]


In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_indexes_axis0 = np.argmin(array1, axis=0)
print("Original array:")
print(array1)
print("\nIndexes with minimum values across axis=0:")
print(min_indexes_axis0)

Original array:
[[9 0 3]
 [7 5 1]
 [6 1 2]
 [4 8 5]]

Indexes with minimum values across axis=0:
[3 0 1]


In [ ]:
# Create an array of normally distributed random numbers
mean = 0   # Mean of the distribution
std_dev = 1   # Standard deviation of the distribution
size = (3, 3)   # Size of the array
normal_array = np.random.normal(mean, std_dev, size)
print("Array of normally distributed random numbers:")
print(normal_array)

Array of normally distributed random numbers:
[[ 0.25056525  0.6633964  -0.86303772]
 [-0.50356356 -1.00104193  0.44495141]
 [-1.67516201  1.2772512   1.04342832]]


In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.linspace(1, 100, 10)
print("Array with 10 evenly spaced numbers between 1 and 100:")
print(evenly_spaced_array)

Array with 10 evenly spaced numbers between 1 and 100:
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.